sudo: required
services: 
  - docker

before_install:
  - docker build -t dennishaller/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dennishaller/docker-react npm run test -- --coverage
 
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-us-east-2-213898942030"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
